### ISSUE TITLE
Are you creator of BlazorForums.net?

### ISSUE THREAD

**Issue by DataJuggler** [ElliottBrand/BlazorResume#6]
If yes, I signed up today, and I never received the confirmation email.

I have tried to login and it I can't. Forgot Password says 'Email Not Verified', but I didn't see a way to resend the email.

Sorry to contact you here, I don't have any of the other services you listed (Twitter, Instagram).

Thanks,

Corby (DataJuggler is my user name).

**Comment by ElliottBrand** [comment]
Your email address didn't have a domain extension on it.

**Comment by DataJuggler** [comment]
Is there a way to correct it?

Thanks,

**Comment by ElliottBrand** [comment]
If you let me know what it should end with (.com, .net, etc.), I can update it.

**Comment by ElliottBrand** [comment]
I found your email through a search and updated your email and marked it as confirmed. You should be able to login now.

Thanks,
Steve

**Comment by DataJuggler** [comment]
.com. My apologies.

Thanks

**Comment by DataJuggler** [comment]
Thank you kindly.
